-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity LeNet_wrapper_SMM_1u_500u_50u_Pipeline_VITIS_LOOP_105_6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    connect_4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    connect_4_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    connect_4_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    connect_4_empty_n : IN STD_LOGIC;
    connect_4_read : OUT STD_LOGIC;
    B_ROW_load : IN STD_LOGIC_VECTOR (31 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_ce1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_we1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_ce1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_we1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_ce1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_we1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_ce1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_we1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_ce1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_we1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_ce1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_we1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_ce1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_we1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_ce1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_we1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_ce1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_we1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_ce1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_we1 : OUT STD_LOGIC;
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_ce1 : OUT STD_LOGIC;
    p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_we1 : OUT STD_LOGIC;
    p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of LeNet_wrapper_SMM_1u_500u_50u_Pipeline_VITIS_LOOP_105_6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv9_1F4 : STD_LOGIC_VECTOR (8 downto 0) := "111110100";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv9_B : STD_LOGIC_VECTOR (8 downto 0) := "000001011";
    constant ap_const_lv19_2E9 : STD_LOGIC_VECTOR (18 downto 0) := "0000000001011101001";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln108_reg_483 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln105_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal connect_4_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal trunc_ln105_fu_361_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln105_reg_479 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln108_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln105_1_fu_420_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal phi_urem_fu_102 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal select_ln105_fu_383_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_phi_urem_load : STD_LOGIC_VECTOR (8 downto 0);
    signal phi_mul_fu_106 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    signal add_ln105_1_fu_404_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal j_1_fu_110 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln105_fu_351_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_j : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln110_fu_435_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln105_fu_357_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln105_2_fu_371_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln105_1_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_410_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_420 : BOOLEAN;
    signal ap_condition_423 : BOOLEAN;
    signal ap_condition_426 : BOOLEAN;
    signal ap_condition_429 : BOOLEAN;
    signal ap_condition_432 : BOOLEAN;
    signal ap_condition_435 : BOOLEAN;
    signal ap_condition_438 : BOOLEAN;
    signal ap_condition_441 : BOOLEAN;
    signal ap_condition_444 : BOOLEAN;
    signal ap_condition_447 : BOOLEAN;
    signal ap_condition_450 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component LeNet_wrapper_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component LeNet_wrapper_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    j_1_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln105_fu_345_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_1_fu_110 <= add_ln105_fu_351_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_1_fu_110 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    phi_mul_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    phi_mul_fu_106 <= ap_const_lv19_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    phi_mul_fu_106 <= add_ln105_1_fu_404_p2;
                end if;
            end if; 
        end if;
    end process;

    phi_urem_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln105_fu_345_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    phi_urem_fu_102 <= select_ln105_fu_383_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    phi_urem_fu_102 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln108_reg_483 <= icmp_ln108_fu_365_p2;
                trunc_ln105_reg_479 <= trunc_ln105_fu_361_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln105_1_fu_404_p2 <= std_logic_vector(unsigned(phi_mul_fu_106) + unsigned(ap_const_lv19_2E9));
    add_ln105_2_fu_371_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_urem_load) + unsigned(ap_const_lv9_1));
    add_ln105_fu_351_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j) + unsigned(ap_const_lv9_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(connect_4_empty_n, icmp_ln108_reg_483)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln108_reg_483 = ap_const_lv1_1) and (connect_4_empty_n = ap_const_logic_0));
    end process;


    ap_condition_420_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, trunc_ln105_reg_479)
    begin
                ap_condition_420 <= (not((trunc_ln105_reg_479 = ap_const_lv4_0)) and not((trunc_ln105_reg_479 = ap_const_lv4_1)) and not((trunc_ln105_reg_479 = ap_const_lv4_2)) and not((trunc_ln105_reg_479 = ap_const_lv4_3)) and not((trunc_ln105_reg_479 = ap_const_lv4_4)) and not((trunc_ln105_reg_479 = ap_const_lv4_5)) and not((trunc_ln105_reg_479 = ap_const_lv4_6)) and not((trunc_ln105_reg_479 = ap_const_lv4_7)) and not((trunc_ln105_reg_479 = ap_const_lv4_8)) and not((trunc_ln105_reg_479 = ap_const_lv4_9)) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_423_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, trunc_ln105_reg_479)
    begin
                ap_condition_423 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_8));
    end process;


    ap_condition_426_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, trunc_ln105_reg_479)
    begin
                ap_condition_426 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_7));
    end process;


    ap_condition_429_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, trunc_ln105_reg_479)
    begin
                ap_condition_429 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_6));
    end process;


    ap_condition_432_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, trunc_ln105_reg_479)
    begin
                ap_condition_432 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_5));
    end process;


    ap_condition_435_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, trunc_ln105_reg_479)
    begin
                ap_condition_435 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_4));
    end process;


    ap_condition_438_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, trunc_ln105_reg_479)
    begin
                ap_condition_438 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_3));
    end process;


    ap_condition_441_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, trunc_ln105_reg_479)
    begin
                ap_condition_441 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_2));
    end process;


    ap_condition_444_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, trunc_ln105_reg_479)
    begin
                ap_condition_444 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_1));
    end process;


    ap_condition_447_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, trunc_ln105_reg_479)
    begin
                ap_condition_447 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_0));
    end process;


    ap_condition_450_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, trunc_ln105_reg_479)
    begin
                ap_condition_450 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_9));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln105_fu_345_p2)
    begin
        if (((icmp_ln105_fu_345_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_1_fu_110)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_j <= j_1_fu_110;
        end if; 
    end process;


    ap_sig_allocacmp_phi_urem_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, phi_urem_fu_102, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_phi_urem_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_phi_urem_load <= phi_urem_fu_102;
        end if; 
    end process;


    connect_4_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, connect_4_empty_n, icmp_ln108_reg_483, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            connect_4_blk_n <= connect_4_empty_n;
        else 
            connect_4_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    connect_4_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            connect_4_read <= ap_const_logic_1;
        else 
            connect_4_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln105_1_fu_377_p2 <= "1" when (unsigned(add_ln105_2_fu_371_p2) < unsigned(ap_const_lv9_B)) else "0";
    icmp_ln105_fu_345_p2 <= "1" when (ap_sig_allocacmp_j = ap_const_lv9_1F4) else "0";
    icmp_ln108_fu_365_p2 <= "1" when (unsigned(zext_ln105_fu_357_p1) < unsigned(B_ROW_load)) else "0";
    p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_address1 <= zext_ln105_1_fu_420_p1(6 - 1 downto 0);

    p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if (((not((trunc_ln105_reg_479 = ap_const_lv4_0)) and not((trunc_ln105_reg_479 = ap_const_lv4_1)) and not((trunc_ln105_reg_479 = ap_const_lv4_2)) and not((trunc_ln105_reg_479 = ap_const_lv4_3)) and not((trunc_ln105_reg_479 = ap_const_lv4_4)) and not((trunc_ln105_reg_479 = ap_const_lv4_5)) and not((trunc_ln105_reg_479 = ap_const_lv4_6)) and not((trunc_ln105_reg_479 = ap_const_lv4_7)) and not((trunc_ln105_reg_479 = ap_const_lv4_8)) and not((trunc_ln105_reg_479 = ap_const_lv4_9)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or (not((trunc_ln105_reg_479 = ap_const_lv4_0)) and not((trunc_ln105_reg_479 = ap_const_lv4_1)) and not((trunc_ln105_reg_479 = ap_const_lv4_2)) and not((trunc_ln105_reg_479 = ap_const_lv4_3)) and not((trunc_ln105_reg_479 = ap_const_lv4_4)) and not((trunc_ln105_reg_479 = ap_const_lv4_5)) and not((trunc_ln105_reg_479 = ap_const_lv4_6)) and not((trunc_ln105_reg_479 
    = ap_const_lv4_7)) and not((trunc_ln105_reg_479 = ap_const_lv4_8)) and not((trunc_ln105_reg_479 = ap_const_lv4_9)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_ce1 <= ap_const_logic_1;
        else 
            p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_d1_assign_proc : process(icmp_ln108_reg_483, trunc_ln110_fu_435_p1, ap_condition_420)
    begin
        if ((ap_const_boolean_1 = ap_condition_420)) then
            if ((icmp_ln108_reg_483 = ap_const_lv1_1)) then 
                p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_d1 <= trunc_ln110_fu_435_p1;
            elsif ((icmp_ln108_reg_483 = ap_const_lv1_0)) then 
                p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_d1 <= ap_const_lv8_0;
            else 
                p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_d1 <= "XXXXXXXX";
            end if;
        else 
            p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_d1 <= "XXXXXXXX";
        end if; 
    end process;


    p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if (((not((trunc_ln105_reg_479 = ap_const_lv4_0)) and not((trunc_ln105_reg_479 = ap_const_lv4_1)) and not((trunc_ln105_reg_479 = ap_const_lv4_2)) and not((trunc_ln105_reg_479 = ap_const_lv4_3)) and not((trunc_ln105_reg_479 = ap_const_lv4_4)) and not((trunc_ln105_reg_479 = ap_const_lv4_5)) and not((trunc_ln105_reg_479 = ap_const_lv4_6)) and not((trunc_ln105_reg_479 = ap_const_lv4_7)) and not((trunc_ln105_reg_479 = ap_const_lv4_8)) and not((trunc_ln105_reg_479 = ap_const_lv4_9)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or (not((trunc_ln105_reg_479 = ap_const_lv4_0)) and not((trunc_ln105_reg_479 = ap_const_lv4_1)) and not((trunc_ln105_reg_479 = ap_const_lv4_2)) and not((trunc_ln105_reg_479 = ap_const_lv4_3)) and not((trunc_ln105_reg_479 = ap_const_lv4_4)) and not((trunc_ln105_reg_479 = ap_const_lv4_5)) and not((trunc_ln105_reg_479 = ap_const_lv4_6)) and not((trunc_ln105_reg_479 
    = ap_const_lv4_7)) and not((trunc_ln105_reg_479 = ap_const_lv4_8)) and not((trunc_ln105_reg_479 = ap_const_lv4_9)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_we1 <= ap_const_logic_1;
        else 
            p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1A_10_we1 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln105_fu_383_p3 <= 
        add_ln105_2_fu_371_p2 when (icmp_ln105_1_fu_377_p2(0) = '1') else 
        ap_const_lv9_0;
    tmp_fu_410_p4 <= phi_mul_fu_106(18 downto 13);
    trunc_ln105_fu_361_p1 <= ap_sig_allocacmp_phi_urem_load(4 - 1 downto 0);
    trunc_ln110_fu_435_p1 <= connect_4_dout(8 - 1 downto 0);
    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_address1 <= zext_ln105_1_fu_420_p1(6 - 1 downto 0);

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_8)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_8)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_ce1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_d1_assign_proc : process(icmp_ln108_reg_483, trunc_ln110_fu_435_p1, ap_condition_423)
    begin
        if ((ap_const_boolean_1 = ap_condition_423)) then
            if ((icmp_ln108_reg_483 = ap_const_lv1_1)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_d1 <= trunc_ln110_fu_435_p1;
            elsif ((icmp_ln108_reg_483 = ap_const_lv1_0)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_d1 <= ap_const_lv8_0;
            else 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_d1 <= "XXXXXXXX";
            end if;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_d1 <= "XXXXXXXX";
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_8)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_8)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_we1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_address1 <= zext_ln105_1_fu_420_p1(6 - 1 downto 0);

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_7)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_7)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_ce1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_d1_assign_proc : process(icmp_ln108_reg_483, trunc_ln110_fu_435_p1, ap_condition_426)
    begin
        if ((ap_const_boolean_1 = ap_condition_426)) then
            if ((icmp_ln108_reg_483 = ap_const_lv1_1)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_d1 <= trunc_ln110_fu_435_p1;
            elsif ((icmp_ln108_reg_483 = ap_const_lv1_0)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_d1 <= ap_const_lv8_0;
            else 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_d1 <= "XXXXXXXX";
            end if;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_d1 <= "XXXXXXXX";
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_7)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_7)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_we1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_2_we1 <= ap_const_logic_0;
        end if; 
    end process;

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_address1 <= zext_ln105_1_fu_420_p1(6 - 1 downto 0);

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_6)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_6)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_ce1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_d1_assign_proc : process(icmp_ln108_reg_483, trunc_ln110_fu_435_p1, ap_condition_429)
    begin
        if ((ap_const_boolean_1 = ap_condition_429)) then
            if ((icmp_ln108_reg_483 = ap_const_lv1_1)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_d1 <= trunc_ln110_fu_435_p1;
            elsif ((icmp_ln108_reg_483 = ap_const_lv1_0)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_d1 <= ap_const_lv8_0;
            else 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_d1 <= "XXXXXXXX";
            end if;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_d1 <= "XXXXXXXX";
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_6)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_6)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_we1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_3_we1 <= ap_const_logic_0;
        end if; 
    end process;

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_address1 <= zext_ln105_1_fu_420_p1(6 - 1 downto 0);

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_5)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_5)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_ce1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_d1_assign_proc : process(icmp_ln108_reg_483, trunc_ln110_fu_435_p1, ap_condition_432)
    begin
        if ((ap_const_boolean_1 = ap_condition_432)) then
            if ((icmp_ln108_reg_483 = ap_const_lv1_1)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_d1 <= trunc_ln110_fu_435_p1;
            elsif ((icmp_ln108_reg_483 = ap_const_lv1_0)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_d1 <= ap_const_lv8_0;
            else 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_d1 <= "XXXXXXXX";
            end if;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_d1 <= "XXXXXXXX";
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_5)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_5)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_we1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_4_we1 <= ap_const_logic_0;
        end if; 
    end process;

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_address1 <= zext_ln105_1_fu_420_p1(6 - 1 downto 0);

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_4)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_4)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_ce1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_d1_assign_proc : process(icmp_ln108_reg_483, trunc_ln110_fu_435_p1, ap_condition_435)
    begin
        if ((ap_const_boolean_1 = ap_condition_435)) then
            if ((icmp_ln108_reg_483 = ap_const_lv1_1)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_d1 <= trunc_ln110_fu_435_p1;
            elsif ((icmp_ln108_reg_483 = ap_const_lv1_0)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_d1 <= ap_const_lv8_0;
            else 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_d1 <= "XXXXXXXX";
            end if;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_d1 <= "XXXXXXXX";
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_4)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_4)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_we1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_5_we1 <= ap_const_logic_0;
        end if; 
    end process;

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_address1 <= zext_ln105_1_fu_420_p1(6 - 1 downto 0);

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_3)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_ce1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_d1_assign_proc : process(icmp_ln108_reg_483, trunc_ln110_fu_435_p1, ap_condition_438)
    begin
        if ((ap_const_boolean_1 = ap_condition_438)) then
            if ((icmp_ln108_reg_483 = ap_const_lv1_1)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_d1 <= trunc_ln110_fu_435_p1;
            elsif ((icmp_ln108_reg_483 = ap_const_lv1_0)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_d1 <= ap_const_lv8_0;
            else 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_d1 <= "XXXXXXXX";
            end if;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_d1 <= "XXXXXXXX";
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_3)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_we1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_6_we1 <= ap_const_logic_0;
        end if; 
    end process;

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_address1 <= zext_ln105_1_fu_420_p1(6 - 1 downto 0);

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_2)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_ce1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_d1_assign_proc : process(icmp_ln108_reg_483, trunc_ln110_fu_435_p1, ap_condition_441)
    begin
        if ((ap_const_boolean_1 = ap_condition_441)) then
            if ((icmp_ln108_reg_483 = ap_const_lv1_1)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_d1 <= trunc_ln110_fu_435_p1;
            elsif ((icmp_ln108_reg_483 = ap_const_lv1_0)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_d1 <= ap_const_lv8_0;
            else 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_d1 <= "XXXXXXXX";
            end if;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_d1 <= "XXXXXXXX";
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_2)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_we1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_7_we1 <= ap_const_logic_0;
        end if; 
    end process;

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_address1 <= zext_ln105_1_fu_420_p1(6 - 1 downto 0);

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_1)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_ce1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_d1_assign_proc : process(icmp_ln108_reg_483, trunc_ln110_fu_435_p1, ap_condition_444)
    begin
        if ((ap_const_boolean_1 = ap_condition_444)) then
            if ((icmp_ln108_reg_483 = ap_const_lv1_1)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_d1 <= trunc_ln110_fu_435_p1;
            elsif ((icmp_ln108_reg_483 = ap_const_lv1_0)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_d1 <= ap_const_lv8_0;
            else 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_d1 <= "XXXXXXXX";
            end if;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_d1 <= "XXXXXXXX";
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_1)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_we1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_8_we1 <= ap_const_logic_0;
        end if; 
    end process;

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_address1 <= zext_ln105_1_fu_420_p1(6 - 1 downto 0);

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_0)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_ce1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_d1_assign_proc : process(icmp_ln108_reg_483, trunc_ln110_fu_435_p1, ap_condition_447)
    begin
        if ((ap_const_boolean_1 = ap_condition_447)) then
            if ((icmp_ln108_reg_483 = ap_const_lv1_1)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_d1 <= trunc_ln110_fu_435_p1;
            elsif ((icmp_ln108_reg_483 = ap_const_lv1_0)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_d1 <= ap_const_lv8_0;
            else 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_d1 <= "XXXXXXXX";
            end if;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_d1 <= "XXXXXXXX";
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_0)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_we1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_9_we1 <= ap_const_logic_0;
        end if; 
    end process;

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_address1 <= zext_ln105_1_fu_420_p1(6 - 1 downto 0);

    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_9)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_9)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_ce1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_d1_assign_proc : process(icmp_ln108_reg_483, trunc_ln110_fu_435_p1, ap_condition_450)
    begin
        if ((ap_const_boolean_1 = ap_condition_450)) then
            if ((icmp_ln108_reg_483 = ap_const_lv1_1)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_d1 <= trunc_ln110_fu_435_p1;
            elsif ((icmp_ln108_reg_483 = ap_const_lv1_0)) then 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_d1 <= ap_const_lv8_0;
            else 
                void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_d1 <= "XXXXXXXX";
            end if;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_d1 <= "XXXXXXXX";
        end if; 
    end process;


    void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln108_reg_483, trunc_ln105_reg_479, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_9)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln108_reg_483 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln105_reg_479 = ap_const_lv4_9)))) then 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_we1 <= ap_const_logic_1;
        else 
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_A_we1 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln105_1_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_410_p4),64));
    zext_ln105_fu_357_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_j),32));
end behav;
