// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module SMM_CIF_0_1_SMM_CIF_0_1_Pipeline_VITIS_LOOP_140_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_a_TVALID,
        in_stream_a_TDATA,
        in_stream_a_TREADY,
        B_ROW_load,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_address1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_ce1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_we1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_d1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_address1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_ce1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_we1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_d1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_address1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_ce1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_we1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_d1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_address1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_ce1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_we1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_d1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_address1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_ce1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_we1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_d1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_address1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_ce1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_we1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_d1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_address1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_ce1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_we1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_d1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_address1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_ce1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_we1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_d1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_address1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_ce1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_we1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_d1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_address1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_ce1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_we1,
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_d1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_address1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_ce1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_we1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_d1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_address1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_ce1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_we1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_d1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_address1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_ce1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_we1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_d1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_address1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_ce1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_we1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_d1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_address1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_ce1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_we1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_d1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_address1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_ce1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_we1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_d1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_address1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_ce1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_we1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_d1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_address1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_ce1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_we1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_d1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_address1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_ce1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_we1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_d1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_address1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_ce1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_we1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_d1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_address1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_ce1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_we1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_d1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_address1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_ce1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_we1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_d1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_address1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_ce1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_we1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_d1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_address1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_ce1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_we1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_d1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_address1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_ce1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_we1,
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_d1
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_a_TVALID;
input  [63:0] in_stream_a_TDATA;
output   in_stream_a_TREADY;
input  [31:0] B_ROW_load;
output  [1:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_address1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_ce1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_we1;
output  [15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_d1;
output  [1:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_address1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_ce1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_we1;
output  [15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_d1;
output  [1:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_address1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_ce1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_we1;
output  [15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_d1;
output  [1:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_address1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_ce1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_we1;
output  [15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_d1;
output  [1:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_address1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_ce1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_we1;
output  [15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_d1;
output  [1:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_address1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_ce1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_we1;
output  [15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_d1;
output  [1:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_address1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_ce1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_we1;
output  [15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_d1;
output  [1:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_address1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_ce1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_we1;
output  [15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_d1;
output  [1:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_address1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_ce1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_we1;
output  [15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_d1;
output  [1:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_address1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_ce1;
output   SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_we1;
output  [15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_d1;
output  [1:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_address1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_ce1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_we1;
output  [15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_d1;
output  [1:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_address1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_ce1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_we1;
output  [15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_d1;
output  [1:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_address1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_ce1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_we1;
output  [15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_d1;
output  [1:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_address1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_ce1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_we1;
output  [15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_d1;
output  [1:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_address1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_ce1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_we1;
output  [15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_d1;
output  [1:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_address1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_ce1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_we1;
output  [15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_d1;
output  [1:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_address1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_ce1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_we1;
output  [15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_d1;
output  [1:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_address1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_ce1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_we1;
output  [15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_d1;
output  [1:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_address1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_ce1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_we1;
output  [15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_d1;
output  [1:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_address1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_ce1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_we1;
output  [15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_d1;
output  [1:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_address1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_ce1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_we1;
output  [15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_d1;
output  [1:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_address1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_ce1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_we1;
output  [15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_d1;
output  [1:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_address1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_ce1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_we1;
output  [15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_d1;
output  [1:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_address1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_ce1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_we1;
output  [15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_d1;
output  [1:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_address1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_ce1;
output   p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_we1;
output  [15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_d1;

reg ap_idle;
reg in_stream_a_TREADY;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_ce1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_we1;
reg[15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_d1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_ce1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_we1;
reg[15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_d1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_ce1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_we1;
reg[15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_d1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_ce1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_we1;
reg[15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_d1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_ce1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_we1;
reg[15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_d1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_ce1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_we1;
reg[15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_d1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_ce1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_we1;
reg[15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_d1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_ce1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_we1;
reg[15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_d1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_ce1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_we1;
reg[15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_d1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_ce1;
reg SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_we1;
reg[15:0] SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_d1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_ce1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_we1;
reg[15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_d1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_ce1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_we1;
reg[15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_d1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_ce1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_we1;
reg[15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_d1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_ce1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_we1;
reg[15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_d1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_ce1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_we1;
reg[15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_d1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_ce1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_we1;
reg[15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_d1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_ce1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_we1;
reg[15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_d1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_ce1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_we1;
reg[15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_d1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_ce1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_we1;
reg[15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_d1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_ce1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_we1;
reg[15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_d1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_ce1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_we1;
reg[15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_d1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_ce1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_we1;
reg[15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_d1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_ce1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_we1;
reg[15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_d1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_ce1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_we1;
reg[15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_d1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_ce1;
reg p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_we1;
reg[15:0] p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_d1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln140_fu_652_p2;
wire   [0:0] icmp_ln143_fu_719_p2;
reg    ap_predicate_op130_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_a_TDATA_blk_n;
wire   [63:0] zext_ln140_1_fu_674_p1;
reg   [6:0] phi_urem_fu_160;
wire   [6:0] select_ln140_fu_769_p3;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_phi_urem_load_1;
reg   [6:0] ap_sig_allocacmp_phi_urem_load;
reg   [13:0] phi_mul_fu_164;
wire   [13:0] add_ln140_1_fu_703_p2;
reg   [13:0] ap_sig_allocacmp_phi_mul_load;
reg   [6:0] j_fu_168;
wire   [6:0] add_ln140_fu_658_p2;
reg   [6:0] ap_sig_allocacmp_j_1;
wire   [4:0] trunc_ln2_fu_709_p4;
wire   [15:0] trunc_ln145_fu_725_p1;
wire   [31:0] zext_ln140_fu_670_p1;
wire   [6:0] add_ln140_2_fu_757_p2;
wire   [0:0] icmp_ln140_1_fu_763_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_646;
reg    ap_condition_649;
reg    ap_condition_652;
reg    ap_condition_655;
reg    ap_condition_658;
reg    ap_condition_661;
reg    ap_condition_664;
reg    ap_condition_667;
reg    ap_condition_670;
reg    ap_condition_673;
reg    ap_condition_676;
reg    ap_condition_679;
reg    ap_condition_682;
reg    ap_condition_685;
reg    ap_condition_688;
reg    ap_condition_691;
reg    ap_condition_694;
reg    ap_condition_697;
reg    ap_condition_700;
reg    ap_condition_703;
reg    ap_condition_706;
reg    ap_condition_709;
reg    ap_condition_712;
reg    ap_condition_715;
reg    ap_condition_552;
reg    ap_condition_569;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 phi_urem_fu_160 = 7'd0;
#0 phi_mul_fu_164 = 14'd0;
#0 j_fu_168 = 7'd0;
#0 ap_done_reg = 1'b0;
end

SMM_CIF_0_1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln140_fu_652_p2 == 1'd0)) begin
            j_fu_168 <= add_ln140_fu_658_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_168 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln140_fu_652_p2 == 1'd0)) begin
            phi_mul_fu_164 <= add_ln140_1_fu_703_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_mul_fu_164 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln140_fu_652_p2 == 1'd0)) begin
            phi_urem_fu_160 <= select_ln140_fu_769_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_urem_fu_160 <= 7'd0;
        end
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd1) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd1) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_ce1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_646)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_d1 = 16'd0;
        end else begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_d1 = 'bx;
        end
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd1) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd1) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_we1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd2) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd2) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_ce1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_649)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_d1 = 16'd0;
        end else begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_d1 = 'bx;
        end
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd2) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd2) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_we1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd3) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd3) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_ce1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_652)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_d1 = 16'd0;
        end else begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_d1 = 'bx;
        end
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd3) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd3) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_we1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd4) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd4) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_ce1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_655)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_d1 = 16'd0;
        end else begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_d1 = 'bx;
        end
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd4) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd4) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_we1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd5) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd5) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_ce1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_658)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_d1 = 16'd0;
        end else begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_d1 = 'bx;
        end
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd5) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd5) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_we1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd6) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd6) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_ce1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_661)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_d1 = 16'd0;
        end else begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_d1 = 'bx;
        end
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd6) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd6) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_we1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd7) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd7) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_ce1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_664)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_d1 = 16'd0;
        end else begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_d1 = 'bx;
        end
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd7) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd7) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_we1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd8) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd8) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_ce1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_667)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_d1 = 16'd0;
        end else begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_d1 = 'bx;
        end
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd8) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd8) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_we1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd9) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd9) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_ce1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_670)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_d1 = 16'd0;
        end else begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_d1 = 'bx;
        end
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd9) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd9) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_we1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd0) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd0) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_ce1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_673)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_d1 = 16'd0;
        end else begin
            SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_d1 = 'bx;
        end
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd0) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd0) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_we1 = 1'b1;
    end else begin
        SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln140_fu_652_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_j_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_168;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_phi_mul_load = 14'd0;
    end else begin
        ap_sig_allocacmp_phi_mul_load = phi_mul_fu_164;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_phi_urem_load = 7'd0;
    end else begin
        ap_sig_allocacmp_phi_urem_load = phi_urem_fu_160;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_phi_urem_load_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_phi_urem_load_1 = phi_urem_fu_160;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_predicate_op130_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        in_stream_a_TDATA_blk_n = in_stream_a_TVALID;
    end else begin
        in_stream_a_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_predicate_op130_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        in_stream_a_TREADY = 1'b1;
    end else begin
        in_stream_a_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd10) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd10) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_ce1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_676)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_d1 = 16'd0;
        end else begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_d1 = 'bx;
        end
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd10) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd10) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_we1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd11) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd11) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_ce1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_679)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_d1 = 16'd0;
        end else begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_d1 = 'bx;
        end
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd11) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd11) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_we1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd12) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd12) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_ce1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_682)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_d1 = 16'd0;
        end else begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_d1 = 'bx;
        end
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd12) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd12) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_we1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd13) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd13) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_ce1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_685)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_d1 = 16'd0;
        end else begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_d1 = 'bx;
        end
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd13) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd13) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_we1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd14) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd14) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_ce1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_688)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_d1 = 16'd0;
        end else begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_d1 = 'bx;
        end
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd14) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd14) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_we1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd15) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd15) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_ce1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_691)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_d1 = 16'd0;
        end else begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_d1 = 'bx;
        end
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd15) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd15) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_we1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd16) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd16) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_ce1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_694)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_d1 = 16'd0;
        end else begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_d1 = 'bx;
        end
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd16) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd16) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_we1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd17) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd17) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_ce1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_697)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_d1 = 16'd0;
        end else begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_d1 = 'bx;
        end
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd17) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd17) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_we1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd18) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd18) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_ce1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_700)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_d1 = 16'd0;
        end else begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_d1 = 'bx;
        end
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd18) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd18) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_we1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd19) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd19) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_ce1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_703)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_d1 = 16'd0;
        end else begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_d1 = 'bx;
        end
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd19) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd19) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_we1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd20) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd20) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_ce1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_706)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_d1 = 16'd0;
        end else begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_d1 = 'bx;
        end
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd20) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd20) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_we1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd21) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd21) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_ce1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_709)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_d1 = 16'd0;
        end else begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_d1 = 'bx;
        end
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd21) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd21) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_we1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd22) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd22) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_ce1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_712)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_d1 = 16'd0;
        end else begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_d1 = 'bx;
        end
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd22) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd22) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_we1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd23) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd23) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_ce1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_715)) begin
        if ((icmp_ln143_fu_719_p2 == 1'd1)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_d1 = trunc_ln145_fu_725_p1;
        end else if ((icmp_ln143_fu_719_p2 == 1'd0)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_d1 = 16'd0;
        end else begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_d1 = 'bx;
        end
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd23) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln2_fu_709_p4 == 5'd23) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_we1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (((((((((trunc_ln2_fu_709_p4 == 5'd30) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0)) | ((trunc_ln2_fu_709_p4 == 5'd31) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd29) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd28) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd27) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd26) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd25) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd24) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0)))) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (((((((((trunc_ln2_fu_709_p4 == 5'd30) & (icmp_ln143_fu_719_p2 
    == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0)) | ((trunc_ln2_fu_709_p4 == 5'd31) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd29) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd28) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd27) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd26) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd25) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd24) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0)))))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_ce1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'b1 == ap_condition_569)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_d1 = trunc_ln145_fu_725_p1;
        end else if ((1'b1 == ap_condition_552)) begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_d1 = 16'd0;
        end else begin
            p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_d1 = 'bx;
        end
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (((((((((trunc_ln2_fu_709_p4 == 5'd30) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0)) | ((trunc_ln2_fu_709_p4 == 5'd31) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd29) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd28) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd27) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd26) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd25) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd24) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0)))) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (((((((((trunc_ln2_fu_709_p4 == 5'd30) & (icmp_ln143_fu_719_p2 
    == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0)) | ((trunc_ln2_fu_709_p4 == 5'd31) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd29) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd28) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd27) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd26) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd25) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd24) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0)))))) begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_we1 = 1'b1;
    end else begin
        p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_1_address1 = zext_ln140_1_fu_674_p1;

assign SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_2_address1 = zext_ln140_1_fu_674_p1;

assign SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_3_address1 = zext_ln140_1_fu_674_p1;

assign SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_4_address1 = zext_ln140_1_fu_674_p1;

assign SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_5_address1 = zext_ln140_1_fu_674_p1;

assign SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_6_address1 = zext_ln140_1_fu_674_p1;

assign SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_7_address1 = zext_ln140_1_fu_674_p1;

assign SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_8_address1 = zext_ln140_1_fu_674_p1;

assign SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_9_address1 = zext_ln140_1_fu_674_p1;

assign SMM_CIF_0_1_stream_AXI_VAL_0_stream_AXI_VAL_0_A_address1 = zext_ln140_1_fu_674_p1;

assign add_ln140_1_fu_703_p2 = (ap_sig_allocacmp_phi_mul_load + 14'd171);

assign add_ln140_2_fu_757_p2 = (ap_sig_allocacmp_phi_urem_load + 7'd1);

assign add_ln140_fu_658_p2 = (ap_sig_allocacmp_j_1 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((ap_predicate_op130_read_state1 == 1'b1) & (in_stream_a_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_552 = (((((((((trunc_ln2_fu_709_p4 == 5'd30) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0)) | ((trunc_ln2_fu_709_p4 == 5'd31) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd29) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd28) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd27) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd26) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd25) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd24) & (icmp_ln143_fu_719_p2 == 1'd0) & (icmp_ln140_fu_652_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_569 = (((((((((trunc_ln2_fu_709_p4 == 5'd30) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0)) | ((trunc_ln2_fu_709_p4 == 5'd31) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd29) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd28) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd27) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd26) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd25) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0))) | ((trunc_ln2_fu_709_p4 == 5'd24) & (icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_646 = ((trunc_ln2_fu_709_p4 == 5'd1) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_649 = ((trunc_ln2_fu_709_p4 == 5'd2) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_652 = ((trunc_ln2_fu_709_p4 == 5'd3) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_655 = ((trunc_ln2_fu_709_p4 == 5'd4) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_658 = ((trunc_ln2_fu_709_p4 == 5'd5) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_661 = ((trunc_ln2_fu_709_p4 == 5'd6) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_664 = ((trunc_ln2_fu_709_p4 == 5'd7) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_667 = ((trunc_ln2_fu_709_p4 == 5'd8) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_670 = ((trunc_ln2_fu_709_p4 == 5'd9) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_673 = ((trunc_ln2_fu_709_p4 == 5'd0) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_676 = ((trunc_ln2_fu_709_p4 == 5'd10) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_679 = ((trunc_ln2_fu_709_p4 == 5'd11) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_682 = ((trunc_ln2_fu_709_p4 == 5'd12) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_685 = ((trunc_ln2_fu_709_p4 == 5'd13) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_688 = ((trunc_ln2_fu_709_p4 == 5'd14) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_691 = ((trunc_ln2_fu_709_p4 == 5'd15) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_694 = ((trunc_ln2_fu_709_p4 == 5'd16) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_697 = ((trunc_ln2_fu_709_p4 == 5'd17) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_700 = ((trunc_ln2_fu_709_p4 == 5'd18) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_703 = ((trunc_ln2_fu_709_p4 == 5'd19) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_706 = ((trunc_ln2_fu_709_p4 == 5'd20) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_709 = ((trunc_ln2_fu_709_p4 == 5'd21) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_712 = ((trunc_ln2_fu_709_p4 == 5'd22) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_condition_715 = ((trunc_ln2_fu_709_p4 == 5'd23) & (icmp_ln140_fu_652_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op130_read_state1 = ((icmp_ln143_fu_719_p2 == 1'd1) & (icmp_ln140_fu_652_p2 == 1'd0));
end

assign icmp_ln140_1_fu_763_p2 = ((add_ln140_2_fu_757_p2 < 7'd3) ? 1'b1 : 1'b0);

assign icmp_ln140_fu_652_p2 = ((ap_sig_allocacmp_j_1 == 7'd75) ? 1'b1 : 1'b0);

assign icmp_ln143_fu_719_p2 = ((zext_ln140_fu_670_p1 < B_ROW_load) ? 1'b1 : 1'b0);

assign p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_10_address1 = zext_ln140_1_fu_674_p1;

assign p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_11_address1 = zext_ln140_1_fu_674_p1;

assign p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_12_address1 = zext_ln140_1_fu_674_p1;

assign p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_13_address1 = zext_ln140_1_fu_674_p1;

assign p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_14_address1 = zext_ln140_1_fu_674_p1;

assign p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_15_address1 = zext_ln140_1_fu_674_p1;

assign p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_16_address1 = zext_ln140_1_fu_674_p1;

assign p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_17_address1 = zext_ln140_1_fu_674_p1;

assign p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_18_address1 = zext_ln140_1_fu_674_p1;

assign p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_19_address1 = zext_ln140_1_fu_674_p1;

assign p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_20_address1 = zext_ln140_1_fu_674_p1;

assign p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_21_address1 = zext_ln140_1_fu_674_p1;

assign p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_22_address1 = zext_ln140_1_fu_674_p1;

assign p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_23_address1 = zext_ln140_1_fu_674_p1;

assign p_ZZ11SMM_CIF_0_1RN3hls6streamI7AXI_VALLi0EEES3_E1A_24_address1 = zext_ln140_1_fu_674_p1;

assign select_ln140_fu_769_p3 = ((icmp_ln140_1_fu_763_p2[0:0] == 1'b1) ? add_ln140_2_fu_757_p2 : 7'd0);

assign trunc_ln145_fu_725_p1 = in_stream_a_TDATA[15:0];

assign trunc_ln2_fu_709_p4 = {{ap_sig_allocacmp_phi_mul_load[13:9]}};

assign zext_ln140_1_fu_674_p1 = ap_sig_allocacmp_phi_urem_load_1;

assign zext_ln140_fu_670_p1 = ap_sig_allocacmp_j_1;

endmodule //SMM_CIF_0_1_SMM_CIF_0_1_Pipeline_VITIS_LOOP_140_6
