# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/accelerator_structure/accelerator_structure.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure || ORIG_REF_NAME==accelerator_structure} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_simple_sum_0_0/accelerator_structure_simple_sum_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_simple_sum_0_0 || ORIG_REF_NAME==accelerator_structure_simple_sum_0_0} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_stream_mult_0_0/accelerator_structure_stream_mult_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_stream_mult_0_0 || ORIG_REF_NAME==accelerator_structure_stream_mult_0_0} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_mult_constant_0_0/accelerator_structure_mult_constant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_mult_constant_0_0 || ORIG_REF_NAME==accelerator_structure_mult_constant_0_0} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_axis_switch_0_0/accelerator_structure_axis_switch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_axis_switch_0_0 || ORIG_REF_NAME==accelerator_structure_axis_switch_0_0} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_axi_dma_0_1/accelerator_structure_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_axi_dma_0_1 || ORIG_REF_NAME==accelerator_structure_axi_dma_0_1} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_axi_dma_0_2/accelerator_structure_axi_dma_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_axi_dma_0_2 || ORIG_REF_NAME==accelerator_structure_axi_dma_0_2} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_processing_system7_0_0/accelerator_structure_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_processing_system7_0_0 || ORIG_REF_NAME==accelerator_structure_processing_system7_0_0} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_proc_sys_reset_0_0/accelerator_structure_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_proc_sys_reset_0_0 || ORIG_REF_NAME==accelerator_structure_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_xbar_3/accelerator_structure_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_xbar_3 || ORIG_REF_NAME==accelerator_structure_xbar_3} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_axi_interconnect_0_2/accelerator_structure_axi_interconnect_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_axi_interconnect_0_2 || ORIG_REF_NAME==accelerator_structure_axi_interconnect_0_2} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_xbar_4/accelerator_structure_xbar_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_xbar_4 || ORIG_REF_NAME==accelerator_structure_xbar_4} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_axi_interconnect_1_0/accelerator_structure_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_axi_interconnect_1_0 || ORIG_REF_NAME==accelerator_structure_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_LeNet_wrapper_0_0/accelerator_structure_LeNet_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_LeNet_wrapper_0_0 || ORIG_REF_NAME==accelerator_structure_LeNet_wrapper_0_0} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_auto_us_0/accelerator_structure_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_auto_us_0 || ORIG_REF_NAME==accelerator_structure_auto_us_0} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_auto_us_1/accelerator_structure_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_auto_us_1 || ORIG_REF_NAME==accelerator_structure_auto_us_1} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_auto_pc_0/accelerator_structure_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_auto_pc_0 || ORIG_REF_NAME==accelerator_structure_auto_pc_0} -quiet] -quiet

# IP: bd/accelerator_structure/ip/accelerator_structure_auto_pc_1/accelerator_structure_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accelerator_structure_auto_pc_1 || ORIG_REF_NAME==accelerator_structure_auto_pc_1} -quiet] -quiet

# XDC: d:/Downloads/vivado2014.4/PYNQ_acc/HW_IP/HW_IP.gen/sources_1/bd/accelerator_structure/accelerator_structure_ooc.xdc
