// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="SCIG_CIF_0_2_SCIG_CIF_0_2,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=12.592000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=16,HLS_SYN_DSP=0,HLS_SYN_FF=1182,HLS_SYN_LUT=6792,HLS_VERSION=2023_2}" *)

module SCIG_CIF_0_2 (
        ap_clk,
        ap_rst_n,
        in_r_TDATA,
        in_r_TVALID,
        in_r_TREADY,
        out_r_TDATA,
        out_r_TVALID,
        out_r_TREADY,
        padValue
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst_n;
input  [63:0] in_r_TDATA;
input   in_r_TVALID;
output   in_r_TREADY;
output  [63:0] out_r_TDATA;
output   out_r_TVALID;
input   out_r_TREADY;
input  [31:0] padValue;

 reg    ap_rst_n_inv;
reg    in_r_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    out_r_TDATA_blk_n;
wire    ap_CS_fsm_state9;
reg    ap_block_state1;
reg    ap_block_state2;
reg    ap_block_state3;
reg    ap_block_state4;
reg    ap_block_state5;
reg    ap_block_state6;
reg    ap_block_state7;
reg    ap_block_state8;
wire   [0:0] icmp_ln131_fu_128_p2;
reg   [0:0] icmp_ln131_reg_166;
wire  signed [31:0] valIn_data_1_fu_134_p1;
reg  signed [31:0] valIn_data_1_reg_170;
wire  signed [31:0] valIn_data_2_fu_138_p1;
reg  signed [31:0] valIn_data_2_reg_175;
wire  signed [31:0] valIn_data_3_fu_142_p1;
reg  signed [31:0] valIn_data_3_reg_181;
wire  signed [31:0] valIn_data_4_fu_146_p1;
reg  signed [31:0] valIn_data_4_reg_186;
wire  signed [31:0] KER_size_0_fu_150_p2;
reg  signed [31:0] KER_size_0_reg_191;
wire   [15:0] empty_fu_154_p1;
reg   [15:0] empty_reg_196;
wire  signed [31:0] KER_size_1_fu_158_p2;
reg  signed [31:0] KER_size_1_reg_201;
wire    ap_CS_fsm_state10;
wire   [31:0] KER_bound_fu_162_p2;
reg   [31:0] KER_bound_reg_206;
wire    ap_CS_fsm_state11;
wire   [31:0] grp_fu_114_p2;
reg   [31:0] mul44_reg_211;
wire    ap_CS_fsm_state14;
wire   [15:0] inElem_q0;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_start;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_done;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_idle;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_ready;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_out_r_TREADY;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_in_r_TREADY;
wire   [63:0] grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_out_r_TDATA;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_out_r_TVALID;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_start;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_done;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_idle;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_ready;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_out_r_TREADY;
wire   [7:0] grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_address0;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_ce0;
wire   [7:0] grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_address1;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_ce1;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_we1;
wire   [15:0] grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_d1;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_in_r_TREADY;
wire   [63:0] grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_out_r_TDATA;
wire    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_out_r_TVALID;
reg    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
reg    grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_start_reg;
reg   [16:0] ap_NS_fsm;
wire    ap_NS_fsm_state15;
wire    ap_CS_fsm_state16;
wire   [13:0] grp_fu_114_p1;
wire   [31:0] valIn_data_fu_124_p1;
reg    grp_fu_114_ce;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    regslice_both_out_r_U_apdone_blk;
wire    ap_CS_fsm_state17;
wire    regslice_both_in_r_U_apdone_blk;
wire   [63:0] in_r_TDATA_int_regslice;
wire    in_r_TVALID_int_regslice;
reg    in_r_TREADY_int_regslice;
wire    regslice_both_in_r_U_ack_in;
reg   [63:0] out_r_TDATA_int_regslice;
reg    out_r_TVALID_int_regslice;
wire    out_r_TREADY_int_regslice;
wire    regslice_both_out_r_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_start_reg = 1'b0;
#0 grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_start_reg = 1'b0;
end

SCIG_CIF_0_2_inElem_RAM_S2P_LUTRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
inElem_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_address0),
    .ce0(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_ce0),
    .q0(inElem_q0),
    .address1(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_address1),
    .ce1(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_ce1),
    .we1(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_we1),
    .d1(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_d1)
);

SCIG_CIF_0_2_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6 grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_start),
    .ap_done(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_done),
    .ap_idle(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_idle),
    .ap_ready(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_ready),
    .in_r_TVALID(in_r_TVALID_int_regslice),
    .out_r_TREADY(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_out_r_TREADY),
    .KER_bound(KER_bound_reg_206),
    .in_r_TDATA(in_r_TDATA_int_regslice),
    .in_r_TREADY(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_in_r_TREADY),
    .out_r_TDATA(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_out_r_TDATA),
    .out_r_TVALID(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_out_r_TVALID)
);

SCIG_CIF_0_2_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1 grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_start),
    .ap_done(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_done),
    .ap_idle(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_idle),
    .ap_ready(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_ready),
    .in_r_TVALID(in_r_TVALID_int_regslice),
    .out_r_TREADY(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_out_r_TREADY),
    .mul44(mul44_reg_211),
    .inElem_address0(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_address0),
    .inElem_ce0(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_ce0),
    .inElem_q0(inElem_q0),
    .inElem_address1(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_address1),
    .inElem_ce1(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_ce1),
    .inElem_we1(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_we1),
    .inElem_d1(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_inElem_d1),
    .empty(empty_reg_196),
    .in_r_TDATA(in_r_TDATA_int_regslice),
    .in_r_TREADY(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_in_r_TREADY),
    .out_r_TDATA(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_out_r_TDATA),
    .out_r_TVALID(grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_out_r_TVALID)
);

SCIG_CIF_0_2_mul_32s_14ns_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
mul_32s_14ns_32_2_1_U10(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(valIn_data_1_reg_170),
    .din1(grp_fu_114_p1),
    .ce(grp_fu_114_ce),
    .dout(grp_fu_114_p2)
);

SCIG_CIF_0_2_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U11(
    .din0(valIn_data_4_reg_186),
    .din1(valIn_data_2_reg_175),
    .dout(KER_size_0_fu_150_p2)
);

SCIG_CIF_0_2_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U12(
    .din0(KER_size_0_reg_191),
    .din1(valIn_data_2_reg_175),
    .dout(KER_size_1_fu_158_p2)
);

SCIG_CIF_0_2_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U13(
    .din0(KER_size_1_reg_201),
    .din1(valIn_data_3_reg_181),
    .dout(KER_bound_fu_162_p2)
);

SCIG_CIF_0_2_regslice_both #(
    .DataWidth( 64 ))
regslice_both_in_r_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_r_TDATA),
    .vld_in(in_r_TVALID),
    .ack_in(regslice_both_in_r_U_ack_in),
    .data_out(in_r_TDATA_int_regslice),
    .vld_out(in_r_TVALID_int_regslice),
    .ack_out(in_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_r_U_apdone_blk)
);

SCIG_CIF_0_2_regslice_both #(
    .DataWidth( 64 ))
regslice_both_out_r_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_r_TDATA_int_regslice),
    .vld_in(out_r_TVALID_int_regslice),
    .ack_in(out_r_TREADY_int_regslice),
    .data_out(out_r_TDATA),
    .vld_out(regslice_both_out_r_U_vld_out),
    .ack_out(out_r_TREADY),
    .apdone_blk(regslice_both_out_r_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state15) & (1'b1 == ap_CS_fsm_state14))) begin
            grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_start_reg <= 1'b1;
        end else if ((grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_ready == 1'b1)) begin
            grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_start_reg <= 1'b1;
        end else if ((grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_ready == 1'b1)) begin
            grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        KER_bound_reg_206 <= KER_bound_fu_162_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        KER_size_0_reg_191 <= KER_size_0_fu_150_p2;
        empty_reg_196 <= empty_fu_154_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        KER_size_1_reg_201 <= KER_size_1_fu_158_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln131_reg_166 <= icmp_ln131_fu_128_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        mul44_reg_211 <= grp_fu_114_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        valIn_data_1_reg_170 <= valIn_data_1_fu_134_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        valIn_data_2_reg_175 <= valIn_data_2_fu_138_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        valIn_data_3_reg_181 <= valIn_data_3_fu_142_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        valIn_data_4_reg_186 <= valIn_data_4_fu_146_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_r_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if (((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state3))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state4))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state5))) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state6))) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state7))) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state8))) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((out_r_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | ((out_r_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
        grp_fu_114_ce = 1'b1;
    end else begin
        grp_fu_114_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        in_r_TDATA_blk_n = in_r_TVALID_int_regslice;
    end else begin
        in_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state8)) & (1'b1 == ap_CS_fsm_state8)) | (~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state7)) & (1'b1 == ap_CS_fsm_state7)) | (~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state6)) & (1'b1 == ap_CS_fsm_state6)) | (~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5)) | (~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state4)) & (1'b1 == ap_CS_fsm_state4)) | (~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3)) | (~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2)) & (1'b1 == ap_CS_fsm_state2)) | (~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_r_TREADY_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        in_r_TREADY_int_regslice = grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_in_r_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        in_r_TREADY_int_regslice = grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_in_r_TREADY;
    end else begin
        in_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        out_r_TDATA_blk_n = out_r_TREADY_int_regslice;
    end else begin
        out_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8)) | ((1'b0 == ap_block_state7) & (1'b1 == ap_CS_fsm_state7)) | ((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6)) | ((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4)) | ((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3)) | ((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2)) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        out_r_TDATA_int_regslice = in_r_TDATA_int_regslice;
    end else if (((grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_out_r_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        out_r_TDATA_int_regslice = grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_out_r_TDATA;
    end else if (((grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_out_r_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        out_r_TDATA_int_regslice = grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_out_r_TDATA;
    end else begin
        out_r_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state8)) & (1'b1 == ap_CS_fsm_state8)) | (~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state7)) & (1'b1 == ap_CS_fsm_state7)) | (~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state6)) & (1'b1 == ap_CS_fsm_state6)) | (~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5)) | (~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state4)) & (1'b1 == ap_CS_fsm_state4)) | (~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3)) | (~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2)) & (1'b1 == ap_CS_fsm_state2)) | (~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        out_r_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        out_r_TVALID_int_regslice = grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_out_r_TVALID;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        out_r_TVALID_int_regslice = grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_out_r_TVALID;
    end else begin
        out_r_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state4)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if ((~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state6)) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state7)) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if ((~((out_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state8)) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((out_r_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state9) & (icmp_ln131_reg_166 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if (((out_r_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state9) & (icmp_ln131_reg_166 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((regslice_both_out_r_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state15 = ap_NS_fsm[32'd14];

always @ (*) begin
    ap_block_state1 = ((out_r_TREADY_int_regslice == 1'b0) | (in_r_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2 = ((out_r_TREADY_int_regslice == 1'b0) | (in_r_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((out_r_TREADY_int_regslice == 1'b0) | (in_r_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state4 = ((out_r_TREADY_int_regslice == 1'b0) | (in_r_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state5 = ((out_r_TREADY_int_regslice == 1'b0) | (in_r_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state6 = ((out_r_TREADY_int_regslice == 1'b0) | (in_r_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state7 = ((out_r_TREADY_int_regslice == 1'b0) | (in_r_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state8 = ((out_r_TREADY_int_regslice == 1'b0) | (in_r_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_fu_154_p1 = padValue[15:0];

assign grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_start = grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_ap_start_reg;

assign grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_155_1_fu_103_out_r_TREADY = (out_r_TREADY_int_regslice & ap_CS_fsm_state16);

assign grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_start = grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_ap_start_reg;

assign grp_SCIG_CIF_0_2_Pipeline_VITIS_LOOP_242_6_fu_94_out_r_TREADY = (out_r_TREADY_int_regslice & ap_CS_fsm_state13);

assign grp_fu_114_p1 = 32'd6520;

assign icmp_ln131_fu_128_p2 = ((valIn_data_fu_124_p1 == 32'd0) ? 1'b1 : 1'b0);

assign in_r_TREADY = regslice_both_in_r_U_ack_in;

assign out_r_TVALID = regslice_both_out_r_U_vld_out;

assign valIn_data_1_fu_134_p1 = in_r_TDATA_int_regslice[31:0];

assign valIn_data_2_fu_138_p1 = in_r_TDATA_int_regslice[31:0];

assign valIn_data_3_fu_142_p1 = in_r_TDATA_int_regslice[31:0];

assign valIn_data_4_fu_146_p1 = in_r_TDATA_int_regslice[31:0];

assign valIn_data_fu_124_p1 = in_r_TDATA_int_regslice[31:0];

endmodule //SCIG_CIF_0_2
