set SynModuleInfo {
  {SRCNAME SCIG_CIF_0_3_Pipeline_VITIS_LOOP_242_6 MODELNAME SCIG_CIF_0_3_Pipeline_VITIS_LOOP_242_6 RTLNAME SCIG_CIF_0_3_SCIG_CIF_0_3_Pipeline_VITIS_LOOP_242_6
    SUBMODULES {
      {MODELNAME SCIG_CIF_0_3_flow_control_loop_pipe_sequential_init RTLNAME SCIG_CIF_0_3_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME SCIG_CIF_0_3_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME SCIG_CIF_0_3_Pipeline_VITIS_LOOP_155_1 MODELNAME SCIG_CIF_0_3_Pipeline_VITIS_LOOP_155_1 RTLNAME SCIG_CIF_0_3_SCIG_CIF_0_3_Pipeline_VITIS_LOOP_155_1
    SUBMODULES {
      {MODELNAME SCIG_CIF_0_3_SCIG_CIF_0_3_Pipeline_VITIS_LOOP_155_1_inputBuf_RAM_AUTO_1R1W RTLNAME SCIG_CIF_0_3_SCIG_CIF_0_3_Pipeline_VITIS_LOOP_155_1_inputBuf_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME SCIG_CIF_0_3 MODELNAME SCIG_CIF_0_3 RTLNAME SCIG_CIF_0_3 IS_TOP 1
    SUBMODULES {
      {MODELNAME SCIG_CIF_0_3_mul_32s_12ns_32_2_1 RTLNAME SCIG_CIF_0_3_mul_32s_12ns_32_2_1 BINDTYPE op TYPE mul IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME SCIG_CIF_0_3_mul_32s_32s_32_1_1 RTLNAME SCIG_CIF_0_3_mul_32s_32s_32_1_1 BINDTYPE op TYPE mul IMPL fabric LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME SCIG_CIF_0_3_inElem_RAM_S2P_LUTRAM_1R1W RTLNAME SCIG_CIF_0_3_inElem_RAM_S2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_s2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME SCIG_CIF_0_3_regslice_both RTLNAME SCIG_CIF_0_3_regslice_both BINDTYPE interface TYPE interface_regslice INSTNAME SCIG_CIF_0_3_regslice_both_U}
    }
  }
}
