set SynModuleInfo {
  {SRCNAME SCIG_CIF_0_1_Pipeline_VITIS_LOOP_241_6 MODELNAME SCIG_CIF_0_1_Pipeline_VITIS_LOOP_241_6 RTLNAME SCIG_CIF_0_1_SCIG_CIF_0_1_Pipeline_VITIS_LOOP_241_6
    SUBMODULES {
      {MODELNAME SCIG_CIF_0_1_flow_control_loop_pipe_sequential_init RTLNAME SCIG_CIF_0_1_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME SCIG_CIF_0_1_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME SCIG_CIF_0_1_Pipeline_VITIS_LOOP_153_1 MODELNAME SCIG_CIF_0_1_Pipeline_VITIS_LOOP_153_1 RTLNAME SCIG_CIF_0_1_SCIG_CIF_0_1_Pipeline_VITIS_LOOP_153_1
    SUBMODULES {
      {MODELNAME SCIG_CIF_0_1_SCIG_CIF_0_1_Pipeline_VITIS_LOOP_153_1_inputBuf_RAM_AUTO_1R1W RTLNAME SCIG_CIF_0_1_SCIG_CIF_0_1_Pipeline_VITIS_LOOP_153_1_inputBuf_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME SCIG_CIF_0_1 MODELNAME SCIG_CIF_0_1 RTLNAME SCIG_CIF_0_1 IS_TOP 1
    SUBMODULES {
      {MODELNAME SCIG_CIF_0_1_mul_32s_16ns_32_2_1 RTLNAME SCIG_CIF_0_1_mul_32s_16ns_32_2_1 BINDTYPE op TYPE mul IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME SCIG_CIF_0_1_mul_32s_32s_32_1_1 RTLNAME SCIG_CIF_0_1_mul_32s_32s_32_1_1 BINDTYPE op TYPE mul IMPL fabric LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME SCIG_CIF_0_1_inElem_RAM_S2P_LUTRAM_1R1W RTLNAME SCIG_CIF_0_1_inElem_RAM_S2P_LUTRAM_1R1W BINDTYPE storage TYPE ram_s2p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME SCIG_CIF_0_1_regslice_both RTLNAME SCIG_CIF_0_1_regslice_both BINDTYPE interface TYPE interface_regslice INSTNAME SCIG_CIF_0_1_regslice_both_U}
    }
  }
}
