// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module LeNet_wrapper_SMM_1u_500u_50u_Pipeline_VITIS_LOOP_78_1_VITIS_LOOP_79_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        connect_4_dout,
        connect_4_num_data_valid,
        connect_4_fifo_cap,
        connect_4_empty_n,
        connect_4_read,
        connect_5_din,
        connect_5_num_data_valid,
        connect_5_fifo_cap,
        connect_5_full_n,
        connect_5_write,
        valIn_a_15,
        mul_ln75_1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_address1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_ce1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_we1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_d1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_address1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_ce1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_we1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_d1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_address1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_ce1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_we1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_d1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_address1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_ce1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_we1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_d1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_address1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_ce1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_we1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_d1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_address1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_ce1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_we1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_d1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_address1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_ce1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_we1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_d1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_address1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_ce1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_we1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_d1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_address1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_ce1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_we1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_d1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_address1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_ce1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_we1,
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_d1,
        p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_address1,
        p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_ce1,
        p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_we1,
        p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] connect_4_dout;
input  [6:0] connect_4_num_data_valid;
input  [6:0] connect_4_fifo_cap;
input   connect_4_empty_n;
output   connect_4_read;
output  [31:0] connect_5_din;
input  [2:0] connect_5_num_data_valid;
input  [2:0] connect_5_fifo_cap;
input   connect_5_full_n;
output   connect_5_write;
input  [31:0] valIn_a_15;
input  [31:0] mul_ln75_1;
output  [11:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_address1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_ce1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_we1;
output  [7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_d1;
output  [11:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_address1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_ce1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_we1;
output  [7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_d1;
output  [11:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_address1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_ce1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_we1;
output  [7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_d1;
output  [11:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_address1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_ce1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_we1;
output  [7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_d1;
output  [11:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_address1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_ce1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_we1;
output  [7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_d1;
output  [11:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_address1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_ce1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_we1;
output  [7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_d1;
output  [11:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_address1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_ce1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_we1;
output  [7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_d1;
output  [11:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_address1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_ce1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_we1;
output  [7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_d1;
output  [11:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_address1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_ce1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_we1;
output  [7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_d1;
output  [11:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_address1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_ce1;
output   void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_we1;
output  [7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_d1;
output  [11:0] p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_address1;
output   p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_ce1;
output   p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_we1;
output  [7:0] p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_d1;

reg ap_idle;
reg connect_4_read;
reg connect_5_write;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_ce1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_we1;
reg[7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_d1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_ce1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_we1;
reg[7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_d1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_ce1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_we1;
reg[7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_d1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_ce1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_we1;
reg[7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_d1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_ce1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_we1;
reg[7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_d1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_ce1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_we1;
reg[7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_d1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_ce1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_we1;
reg[7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_d1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_ce1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_we1;
reg[7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_d1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_ce1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_we1;
reg[7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_d1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_ce1;
reg void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_we1;
reg[7:0] void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_d1;
reg p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_ce1;
reg p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_we1;
reg[7:0] p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_d1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_idle_pp0;
reg   [0:0] or_ln82_reg_606;
reg   [0:0] or_ln82_reg_606_pp0_iter12_reg;
reg    ap_block_state14_pp0_stage0_iter13;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln78_fu_374_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    connect_5_blk_n;
wire    ap_block_pp0_stage0;
reg    connect_4_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln79_fu_389_p2;
reg   [0:0] icmp_ln79_reg_580;
reg   [0:0] icmp_ln79_reg_580_pp0_iter1_reg;
reg   [0:0] icmp_ln79_reg_580_pp0_iter2_reg;
reg   [0:0] icmp_ln79_reg_580_pp0_iter3_reg;
reg   [0:0] icmp_ln79_reg_580_pp0_iter4_reg;
reg   [0:0] icmp_ln79_reg_580_pp0_iter5_reg;
reg   [0:0] icmp_ln79_reg_580_pp0_iter6_reg;
reg   [0:0] icmp_ln79_reg_580_pp0_iter7_reg;
reg   [0:0] icmp_ln79_reg_580_pp0_iter8_reg;
reg   [0:0] icmp_ln79_reg_580_pp0_iter9_reg;
wire   [8:0] select_ln78_fu_395_p3;
reg   [8:0] select_ln78_reg_585;
wire   [0:0] icmp_ln82_fu_413_p2;
reg   [0:0] icmp_ln82_reg_591;
reg   [0:0] icmp_ln82_reg_591_pp0_iter1_reg;
reg   [0:0] icmp_ln82_reg_591_pp0_iter2_reg;
reg   [0:0] icmp_ln82_reg_591_pp0_iter3_reg;
reg   [0:0] icmp_ln82_reg_591_pp0_iter4_reg;
reg   [0:0] icmp_ln82_reg_591_pp0_iter5_reg;
reg   [0:0] icmp_ln82_reg_591_pp0_iter6_reg;
reg   [0:0] icmp_ln82_reg_591_pp0_iter7_reg;
reg   [0:0] icmp_ln82_reg_591_pp0_iter8_reg;
reg   [0:0] icmp_ln82_reg_591_pp0_iter9_reg;
reg   [5:0] tmp_reg_596;
reg   [5:0] tmp_reg_596_pp0_iter2_reg;
reg   [5:0] tmp_reg_596_pp0_iter3_reg;
reg   [5:0] tmp_reg_596_pp0_iter4_reg;
reg   [5:0] tmp_reg_596_pp0_iter5_reg;
reg   [5:0] tmp_reg_596_pp0_iter6_reg;
reg   [5:0] tmp_reg_596_pp0_iter7_reg;
reg   [5:0] tmp_reg_596_pp0_iter8_reg;
reg   [5:0] tmp_reg_596_pp0_iter9_reg;
reg   [5:0] tmp_reg_596_pp0_iter10_reg;
reg   [5:0] tmp_reg_596_pp0_iter11_reg;
wire   [0:0] or_ln82_fu_494_p2;
reg   [0:0] or_ln82_reg_606_pp0_iter11_reg;
wire   [3:0] trunc_ln79_fu_508_p1;
reg   [3:0] trunc_ln79_reg_615;
wire   [63:0] zext_ln84_2_fu_512_p1;
reg   [8:0] j_fu_120;
wire   [8:0] add_ln79_fu_419_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_j_load;
reg   [5:0] i_4_fu_124;
wire   [5:0] select_ln78_1_fu_463_p3;
reg   [14:0] indvar_flatten_fu_128;
wire   [14:0] add_ln78_1_fu_380_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] trunc_ln84_fu_526_p1;
wire   [4:0] grp_fu_407_p1;
wire   [31:0] zext_ln79_fu_403_p1;
wire   [8:0] mul_ln79_fu_438_p0;
wire   [10:0] mul_ln79_fu_438_p1;
wire   [18:0] mul_ln79_fu_438_p2;
wire   [5:0] add_ln78_fu_457_p2;
wire   [31:0] zext_ln78_fu_474_p1;
wire   [0:0] ult_fu_478_p2;
wire   [0:0] xor_ln82_fu_489_p2;
wire   [0:0] rev_fu_483_p2;
wire   [3:0] grp_fu_407_p2;
wire   [11:0] grp_fu_541_p3;
wire   [5:0] grp_fu_541_p0;
wire   [5:0] grp_fu_541_p1;
wire   [5:0] grp_fu_541_p2;
reg    grp_fu_407_ce;
reg    grp_fu_541_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [11:0] grp_fu_541_p00;
wire   [11:0] grp_fu_541_p20;
wire   [18:0] mul_ln79_fu_438_p00;
reg    ap_condition_654;
reg    ap_condition_657;
reg    ap_condition_660;
reg    ap_condition_663;
reg    ap_condition_666;
reg    ap_condition_669;
reg    ap_condition_672;
reg    ap_condition_675;
reg    ap_condition_678;
reg    ap_condition_681;
reg    ap_condition_684;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 j_fu_120 = 9'd0;
#0 i_4_fu_124 = 6'd0;
#0 indvar_flatten_fu_128 = 15'd0;
#0 ap_done_reg = 1'b0;
end

LeNet_wrapper_urem_9ns_5ns_4_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 4 ))
urem_9ns_5ns_4_13_1_U271(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln78_fu_395_p3),
    .din1(grp_fu_407_p1),
    .ce(grp_fu_407_ce),
    .dout(grp_fu_407_p2)
);

LeNet_wrapper_mul_9ns_11ns_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
mul_9ns_11ns_19_1_1_U272(
    .din0(mul_ln79_fu_438_p0),
    .din1(mul_ln79_fu_438_p1),
    .dout(mul_ln79_fu_438_p2)
);

LeNet_wrapper_mac_muladd_6ns_6ns_6ns_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mac_muladd_6ns_6ns_6ns_12_4_1_U273(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_541_p0),
    .din1(grp_fu_541_p1),
    .din2(grp_fu_541_p2),
    .ce(grp_fu_541_ce),
    .dout(grp_fu_541_p3)
);

LeNet_wrapper_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            i_4_fu_124 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter10 == 1'b1)) begin
            i_4_fu_124 <= select_ln78_1_fu_463_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln78_fu_374_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_128 <= add_ln78_1_fu_380_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_128 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln78_fu_374_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_120 <= add_ln79_fu_419_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_120 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln79_reg_580_pp0_iter2_reg <= icmp_ln79_reg_580_pp0_iter1_reg;
        icmp_ln79_reg_580_pp0_iter3_reg <= icmp_ln79_reg_580_pp0_iter2_reg;
        icmp_ln79_reg_580_pp0_iter4_reg <= icmp_ln79_reg_580_pp0_iter3_reg;
        icmp_ln79_reg_580_pp0_iter5_reg <= icmp_ln79_reg_580_pp0_iter4_reg;
        icmp_ln79_reg_580_pp0_iter6_reg <= icmp_ln79_reg_580_pp0_iter5_reg;
        icmp_ln79_reg_580_pp0_iter7_reg <= icmp_ln79_reg_580_pp0_iter6_reg;
        icmp_ln79_reg_580_pp0_iter8_reg <= icmp_ln79_reg_580_pp0_iter7_reg;
        icmp_ln79_reg_580_pp0_iter9_reg <= icmp_ln79_reg_580_pp0_iter8_reg;
        icmp_ln82_reg_591_pp0_iter2_reg <= icmp_ln82_reg_591_pp0_iter1_reg;
        icmp_ln82_reg_591_pp0_iter3_reg <= icmp_ln82_reg_591_pp0_iter2_reg;
        icmp_ln82_reg_591_pp0_iter4_reg <= icmp_ln82_reg_591_pp0_iter3_reg;
        icmp_ln82_reg_591_pp0_iter5_reg <= icmp_ln82_reg_591_pp0_iter4_reg;
        icmp_ln82_reg_591_pp0_iter6_reg <= icmp_ln82_reg_591_pp0_iter5_reg;
        icmp_ln82_reg_591_pp0_iter7_reg <= icmp_ln82_reg_591_pp0_iter6_reg;
        icmp_ln82_reg_591_pp0_iter8_reg <= icmp_ln82_reg_591_pp0_iter7_reg;
        icmp_ln82_reg_591_pp0_iter9_reg <= icmp_ln82_reg_591_pp0_iter8_reg;
        or_ln82_reg_606 <= or_ln82_fu_494_p2;
        or_ln82_reg_606_pp0_iter11_reg <= or_ln82_reg_606;
        or_ln82_reg_606_pp0_iter12_reg <= or_ln82_reg_606_pp0_iter11_reg;
        tmp_reg_596_pp0_iter10_reg <= tmp_reg_596_pp0_iter9_reg;
        tmp_reg_596_pp0_iter11_reg <= tmp_reg_596_pp0_iter10_reg;
        tmp_reg_596_pp0_iter2_reg <= tmp_reg_596;
        tmp_reg_596_pp0_iter3_reg <= tmp_reg_596_pp0_iter2_reg;
        tmp_reg_596_pp0_iter4_reg <= tmp_reg_596_pp0_iter3_reg;
        tmp_reg_596_pp0_iter5_reg <= tmp_reg_596_pp0_iter4_reg;
        tmp_reg_596_pp0_iter6_reg <= tmp_reg_596_pp0_iter5_reg;
        tmp_reg_596_pp0_iter7_reg <= tmp_reg_596_pp0_iter6_reg;
        tmp_reg_596_pp0_iter8_reg <= tmp_reg_596_pp0_iter7_reg;
        tmp_reg_596_pp0_iter9_reg <= tmp_reg_596_pp0_iter8_reg;
        trunc_ln79_reg_615 <= trunc_ln79_fu_508_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln79_reg_580 <= icmp_ln79_fu_389_p2;
        icmp_ln79_reg_580_pp0_iter1_reg <= icmp_ln79_reg_580;
        icmp_ln82_reg_591 <= icmp_ln82_fu_413_p2;
        icmp_ln82_reg_591_pp0_iter1_reg <= icmp_ln82_reg_591;
        select_ln78_reg_585 <= select_ln78_fu_395_p3;
        tmp_reg_596 <= {{mul_ln79_fu_438_p2[18:13]}};
    end
end

always @ (*) begin
    if (((icmp_ln78_fu_374_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_128;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 9'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_120;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        connect_4_blk_n = connect_4_empty_n;
    end else begin
        connect_4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        connect_4_read = 1'b1;
    end else begin
        connect_4_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        connect_5_blk_n = connect_5_full_n;
    end else begin
        connect_5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        connect_5_write = 1'b1;
    end else begin
        connect_5_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_407_ce = 1'b1;
    end else begin
        grp_fu_407_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_541_ce = 1'b1;
    end else begin
        grp_fu_541_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~(trunc_ln79_reg_615 == 4'd0) & ~(trunc_ln79_reg_615 == 4'd1) & ~(trunc_ln79_reg_615 == 4'd2) & ~(trunc_ln79_reg_615 == 4'd3) & ~(trunc_ln79_reg_615 == 4'd4) & ~(trunc_ln79_reg_615 == 4'd5) & ~(trunc_ln79_reg_615 == 4'd6) & ~(trunc_ln79_reg_615 == 4'd7) & ~(trunc_ln79_reg_615 == 4'd8) & ~(trunc_ln79_reg_615 == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1)) | (~(trunc_ln79_reg_615 == 4'd0) & ~(trunc_ln79_reg_615 == 4'd1) & ~(trunc_ln79_reg_615 == 4'd2) & ~(trunc_ln79_reg_615 == 4'd3) & ~(trunc_ln79_reg_615 == 4'd4) & ~(trunc_ln79_reg_615 == 4'd5) & ~(trunc_ln79_reg_615 == 4'd6) & ~(trunc_ln79_reg_615 == 4'd7) & ~(trunc_ln79_reg_615 == 4'd8) & ~(trunc_ln79_reg_615 == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1)))) begin
        p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_ce1 = 1'b1;
    end else begin
        p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_654)) begin
        if ((or_ln82_reg_606_pp0_iter12_reg == 1'd1)) begin
            p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_d1 = 8'd0;
        end else if ((or_ln82_reg_606_pp0_iter12_reg == 1'd0)) begin
            p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_d1 = trunc_ln84_fu_526_p1;
        end else begin
            p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_d1 = 'bx;
        end
    end else begin
        p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(trunc_ln79_reg_615 == 4'd0) & ~(trunc_ln79_reg_615 == 4'd1) & ~(trunc_ln79_reg_615 == 4'd2) & ~(trunc_ln79_reg_615 == 4'd3) & ~(trunc_ln79_reg_615 == 4'd4) & ~(trunc_ln79_reg_615 == 4'd5) & ~(trunc_ln79_reg_615 == 4'd6) & ~(trunc_ln79_reg_615 == 4'd7) & ~(trunc_ln79_reg_615 == 4'd8) & ~(trunc_ln79_reg_615 == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1)) | (~(trunc_ln79_reg_615 == 4'd0) & ~(trunc_ln79_reg_615 == 4'd1) & ~(trunc_ln79_reg_615 == 4'd2) & ~(trunc_ln79_reg_615 == 4'd3) & ~(trunc_ln79_reg_615 == 4'd4) & ~(trunc_ln79_reg_615 == 4'd5) & ~(trunc_ln79_reg_615 == 4'd6) & ~(trunc_ln79_reg_615 == 4'd7) & ~(trunc_ln79_reg_615 == 4'd8) & ~(trunc_ln79_reg_615 == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1)))) begin
        p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_we1 = 1'b1;
    end else begin
        p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd8)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd8)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_ce1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_657)) begin
        if ((or_ln82_reg_606_pp0_iter12_reg == 1'd1)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_d1 = 8'd0;
        end else if ((or_ln82_reg_606_pp0_iter12_reg == 1'd0)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_d1 = trunc_ln84_fu_526_p1;
        end else begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_d1 = 'bx;
        end
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd8)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd8)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_we1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd7)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd7)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_ce1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_660)) begin
        if ((or_ln82_reg_606_pp0_iter12_reg == 1'd1)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_d1 = 8'd0;
        end else if ((or_ln82_reg_606_pp0_iter12_reg == 1'd0)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_d1 = trunc_ln84_fu_526_p1;
        end else begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_d1 = 'bx;
        end
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd7)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd7)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_we1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd6)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd6)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_ce1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_663)) begin
        if ((or_ln82_reg_606_pp0_iter12_reg == 1'd1)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_d1 = 8'd0;
        end else if ((or_ln82_reg_606_pp0_iter12_reg == 1'd0)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_d1 = trunc_ln84_fu_526_p1;
        end else begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_d1 = 'bx;
        end
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd6)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd6)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_we1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd5)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd5)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_ce1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_666)) begin
        if ((or_ln82_reg_606_pp0_iter12_reg == 1'd1)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_d1 = 8'd0;
        end else if ((or_ln82_reg_606_pp0_iter12_reg == 1'd0)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_d1 = trunc_ln84_fu_526_p1;
        end else begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_d1 = 'bx;
        end
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd5)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd5)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_we1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd4)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_ce1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_669)) begin
        if ((or_ln82_reg_606_pp0_iter12_reg == 1'd1)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_d1 = 8'd0;
        end else if ((or_ln82_reg_606_pp0_iter12_reg == 1'd0)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_d1 = trunc_ln84_fu_526_p1;
        end else begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_d1 = 'bx;
        end
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd4)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_we1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd3)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_ce1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_672)) begin
        if ((or_ln82_reg_606_pp0_iter12_reg == 1'd1)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_d1 = 8'd0;
        end else if ((or_ln82_reg_606_pp0_iter12_reg == 1'd0)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_d1 = trunc_ln84_fu_526_p1;
        end else begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_d1 = 'bx;
        end
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd3)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_we1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd2)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_ce1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_675)) begin
        if ((or_ln82_reg_606_pp0_iter12_reg == 1'd1)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_d1 = 8'd0;
        end else if ((or_ln82_reg_606_pp0_iter12_reg == 1'd0)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_d1 = trunc_ln84_fu_526_p1;
        end else begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_d1 = 'bx;
        end
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd2)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_we1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd1)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_ce1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_678)) begin
        if ((or_ln82_reg_606_pp0_iter12_reg == 1'd1)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_d1 = 8'd0;
        end else if ((or_ln82_reg_606_pp0_iter12_reg == 1'd0)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_d1 = trunc_ln84_fu_526_p1;
        end else begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_d1 = 'bx;
        end
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd1)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_we1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd0)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_ce1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_681)) begin
        if ((or_ln82_reg_606_pp0_iter12_reg == 1'd1)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_d1 = 8'd0;
        end else if ((or_ln82_reg_606_pp0_iter12_reg == 1'd0)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_d1 = trunc_ln84_fu_526_p1;
        end else begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_d1 = 'bx;
        end
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd0)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_we1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd9)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd9)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_ce1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_684)) begin
        if ((or_ln82_reg_606_pp0_iter12_reg == 1'd1)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_d1 = 8'd0;
        end else if ((or_ln82_reg_606_pp0_iter12_reg == 1'd0)) begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_d1 = trunc_ln84_fu_526_p1;
        end else begin
            void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_d1 = 'bx;
        end
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd9)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln82_reg_606_pp0_iter12_reg == 1'd1) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd9)))) begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_we1 = 1'b1;
    end else begin
        void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln78_1_fu_380_p2 = (ap_sig_allocacmp_indvar_flatten_load + 15'd1);

assign add_ln78_fu_457_p2 = (i_4_fu_124 + 6'd1);

assign add_ln79_fu_419_p2 = (select_ln78_fu_395_p3 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage0_iter13));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage0_iter13));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage0_iter13));
end

always @ (*) begin
    ap_block_state14_pp0_stage0_iter13 = (((connect_5_full_n == 1'b0) & (or_ln82_reg_606_pp0_iter12_reg == 1'd0)) | ((or_ln82_reg_606_pp0_iter12_reg == 1'd0) & (connect_4_empty_n == 1'b0)));
end

always @ (*) begin
    ap_condition_654 = (~(trunc_ln79_reg_615 == 4'd0) & ~(trunc_ln79_reg_615 == 4'd1) & ~(trunc_ln79_reg_615 == 4'd2) & ~(trunc_ln79_reg_615 == 4'd3) & ~(trunc_ln79_reg_615 == 4'd4) & ~(trunc_ln79_reg_615 == 4'd5) & ~(trunc_ln79_reg_615 == 4'd6) & ~(trunc_ln79_reg_615 == 4'd7) & ~(trunc_ln79_reg_615 == 4'd8) & ~(trunc_ln79_reg_615 == 4'd9) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1));
end

always @ (*) begin
    ap_condition_657 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd8));
end

always @ (*) begin
    ap_condition_660 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd7));
end

always @ (*) begin
    ap_condition_663 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd6));
end

always @ (*) begin
    ap_condition_666 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd5));
end

always @ (*) begin
    ap_condition_669 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd4));
end

always @ (*) begin
    ap_condition_672 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd3));
end

always @ (*) begin
    ap_condition_675 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd2));
end

always @ (*) begin
    ap_condition_678 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd1));
end

always @ (*) begin
    ap_condition_681 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd0));
end

always @ (*) begin
    ap_condition_684 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln79_reg_615 == 4'd9));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign connect_5_din = connect_4_dout;

assign grp_fu_407_p1 = 9'd11;

assign grp_fu_541_p0 = grp_fu_541_p00;

assign grp_fu_541_p00 = select_ln78_1_fu_463_p3;

assign grp_fu_541_p1 = 12'd46;

assign grp_fu_541_p2 = grp_fu_541_p20;

assign grp_fu_541_p20 = tmp_reg_596_pp0_iter11_reg;

assign icmp_ln78_fu_374_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 15'd25000) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_389_p2 = ((ap_sig_allocacmp_j_load == 9'd500) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_413_p2 = ((zext_ln79_fu_403_p1 < mul_ln75_1) ? 1'b1 : 1'b0);

assign mul_ln79_fu_438_p0 = mul_ln79_fu_438_p00;

assign mul_ln79_fu_438_p00 = select_ln78_reg_585;

assign mul_ln79_fu_438_p1 = 19'd745;

assign or_ln82_fu_494_p2 = (xor_ln82_fu_489_p2 | rev_fu_483_p2);

assign p_ZZ3SMMILj1ELj500ELj50EEvRN3hls6streamI6ap_intILi32EELi0EEES5_jjiE1B_10_address1 = zext_ln84_2_fu_512_p1;

assign rev_fu_483_p2 = (ult_fu_478_p2 ^ 1'd1);

assign select_ln78_1_fu_463_p3 = ((icmp_ln79_reg_580_pp0_iter9_reg[0:0] == 1'b1) ? add_ln78_fu_457_p2 : i_4_fu_124);

assign select_ln78_fu_395_p3 = ((icmp_ln79_fu_389_p2[0:0] == 1'b1) ? 9'd0 : ap_sig_allocacmp_j_load);

assign trunc_ln79_fu_508_p1 = grp_fu_407_p2[3:0];

assign trunc_ln84_fu_526_p1 = connect_4_dout[7:0];

assign ult_fu_478_p2 = ((zext_ln78_fu_474_p1 < valIn_a_15) ? 1'b1 : 1'b0);

assign void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_1_address1 = zext_ln84_2_fu_512_p1;

assign void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_2_address1 = zext_ln84_2_fu_512_p1;

assign void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_3_address1 = zext_ln84_2_fu_512_p1;

assign void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_4_address1 = zext_ln84_2_fu_512_p1;

assign void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_5_address1 = zext_ln84_2_fu_512_p1;

assign void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_6_address1 = zext_ln84_2_fu_512_p1;

assign void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_7_address1 = zext_ln84_2_fu_512_p1;

assign void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_8_address1 = zext_ln84_2_fu_512_p1;

assign void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_9_address1 = zext_ln84_2_fu_512_p1;

assign void_SMM_stream_stream_ap_int_32_0_unsigned_int_unsigned_int_int_B_address1 = zext_ln84_2_fu_512_p1;

assign xor_ln82_fu_489_p2 = (icmp_ln82_reg_591_pp0_iter9_reg ^ 1'd1);

assign zext_ln78_fu_474_p1 = select_ln78_1_fu_463_p3;

assign zext_ln79_fu_403_p1 = select_ln78_fu_395_p3;

assign zext_ln84_2_fu_512_p1 = grp_fu_541_p3;

endmodule //LeNet_wrapper_SMM_1u_500u_50u_Pipeline_VITIS_LOOP_78_1_VITIS_LOOP_79_2
